// Command sk is the daily-use entrypoint for 38specialK.
//
// Slugs are top-level shell functions (kclo, ksys, ...) generated by
// `sk install`. Each function calls back into `sk dispatch <name>` with its
// own name as context; the binary looks up the namespace in
// ~/.config/sk/slugs.yaml and runs the appropriate kubectl command.
//
// You rarely invoke `sk` directly — you invoke the generated slugs.
// `sk` is the engine under the hood. An optional `skd` alias
// (`alias skd="sk dispatch"`) is also emitted by `sk install` for users
// who prefer `skd clo` over `kclo`.
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/weefarm/38specialK/internal/config"
	"github.com/weefarm/38specialK/internal/dispatch"
	"github.com/weefarm/38specialK/internal/install"
)

var (
	cfgPath     string
	dryRun      bool
	versionFlag bool
)

const version = "0.1.0"

func main() {
	root := &cobra.Command{
		Use:   "sk",
		Short: "38specialK — Kubernetes namespace slugs with finalizer ops",
		Long: `38specialK (sk) reduces wasted keystrokes interacting with Kubernetes.

Instead of ` + "`kubectl get pods -n cloudflare -o wide`" + `, you type ` + "`kclo o`" + `.

Slugs are generated by ` + "`sk install`" + ` from ~/.config/sk/slugs.yaml.
Each slug calls back into ` + "`sk dispatch <name>`" + `, which looks up the
namespace and runs the appropriate kubectl command.

A "slug" is a short namespace alias. ` + "`kclo`" + ` dispatches to the
` + "`cloudflare`" + ` namespace — ` + "`k`" + ` is the prefix, ` + "`clo`" + ` is the slug.

Verbs (handled by the dispatcher, not kubectl):
  o    -o wide (or custom -o format if more args follow)
  lsf   list resources with finalizers set in the namespace
  rmf   strip finalizers from a resource so it can finish deleting

Built-in cluster-scoped getters (no namespace):
  kgn        kubectl get nodes        (kgn o -> -o wide)
  kns        kubectl get namespaces   (kns o -> -o wide)

Anything else is passed through to kubectl -n <ns>.`,
	}

	root.PersistentFlags().StringVarP(&cfgPath, "config", "c", "", "path to slugs.yaml (default: ~/.config/sk/slugs.yaml)")
	root.PersistentFlags().BoolVar(&dryRun, "dry-run", false, "print the kubectl command instead of running it")
	root.PersistentFlags().BoolVarP(&versionFlag, "version", "V", false, "print version and exit")

	root.RunE = func(cmd *cobra.Command, args []string) error {
		if versionFlag {
			fmt.Println("38specialK v" + version)
			return nil
		}
		return cmd.Help()
	}

	root.AddCommand(dispatchCmd(), installCmd(), initCmd(), listCmd())

	if err := root.Execute(); err != nil {
		os.Exit(1)
	}
}

// dispatchCmd implements `sk dispatch <name> [args...]`.
func dispatchCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "dispatch <slug-name> [args...]",
		Short: "Run the appropriate kubectl command for a slug",
		Long: `Resolves <slug-name> against the config and dispatches the args.
This is what the generated shell functions call; you usually don't invoke it
directly. You can also use the ` + "`skd`" + ` alias (` + "`alias skd=\"sk dispatch\"`" + `)
emitted by ` + "`sk install`" + ` to do ` + "`skd clo`" + ` instead of ` + "`kclo`" + `.

Examples:
  sk dispatch clo                 # kubectl get pods -n cloudflare
  sk dispatch clo o               # kubectl get pods -n cloudflare -o wide
  sk dispatch clo lsf              # list resources with finalizers in cloudflare
  sk dispatch clo rmf deployment foo  # strip finalizers from deployment/foo
  sk dispatch clo get deploy      # kubectl -n cloudflare get deploy
  sk dispatch all lsf              # whole-cluster finalizer scan
  sk dispatch cil                 # filtered: kube-system pods | grep cilium
  sk dispatch gn                  # kubectl get nodes (built-in cluster getter)
  sk dispatch gn o                # kubectl get nodes -o wide
  sk dispatch ns                  # kubectl get namespaces`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := loadConfig()
			if err != nil {
				return err
			}
			return dispatch.Dispatch(cfg, args[0], args[1:], dispatch.Options{DryRun: dryRun})
		},
		SilenceUsage: true,
	}
	// Everything after the slug name belongs to kubectl, including flags
	// (`kclo delete pod foo --force`). Stop flag parsing at the slug name so
	// sk's own flags must precede it and kubectl flags pass through untouched.
	c.Flags().SetInterspersed(false)
	return c
}

// installCmd implements `sk install` — emits the shell snippet.
func installCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "install",
		Short: "Emit shell functions for all slugs (source from ~/.bashrc)",
		Long: `Prints a shell snippet defining one function per slug in your config,
plus an ` + "`skd`" + ` alias for alternate invocation. Source the output from your
shell rc file:

    sk install >> ~/.bashrc

Or write to a standalone file and source that:

    sk install > ~/.config/sk/slugs.sh
    echo 'source ~/.config/sk/slugs.sh' >> ~/.bashrc

Re-run after editing ~/.config/sk/slugs.yaml.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := loadConfig()
			if err != nil {
				return err
			}
			return install.Emit(cfg, os.Stdout)
		},
		SilenceUsage: true,
	}
}

// initCmd implements `sk init` — writes a starter config.
func initCmd() *cobra.Command {
	var force bool
	c := &cobra.Command{
		Use:   "init",
		Short: "Write a starter slugs.yaml with example slugs",
		Long: `Writes a starter config to ~/.config/sk/slugs.yaml (or --config PATH)
with a small set of example slugs. Edit it to match your namespaces,
then run ` + "`sk install`" + `.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			path, err := configPath()
			if err != nil {
				return err
			}
			return config.WriteExample(path, force)
		},
		SilenceUsage: true,
	}
	c.Flags().BoolVar(&force, "force", false, "overwrite an existing config file")
	return c
}

// listCmd implements `sk list` — shows the loaded config.
func listCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "Show the slugs in the loaded config",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := loadConfig()
			if err != nil {
				return err
			}
			fmt.Print(cfg.String())
			fmt.Println("Slugs:")
			for _, name := range cfg.Names() {
				ns, filtered, _ := cfg.ResolveSlug(name)
				if filtered != nil {
					fmt.Printf("  k%s -> %s (grep %q)\n", name, ns, filtered.Grep)
				} else {
					fmt.Printf("  k%s -> %s\n", name, ns)
				}
			}
			fmt.Printf("  k%s -> all-namespaces\n", cfg.AllSlug)
			return nil
		},
		SilenceUsage: true,
	}
}

// loadConfig resolves the config path and loads it.
func loadConfig() (*config.Config, error) {
	path, err := configPath()
	if err != nil {
		return nil, err
	}
	return config.Load(path)
}

// configPath returns the --config flag value or the default path.
func configPath() (string, error) {
	if cfgPath != "" {
		return cfgPath, nil
	}
	return config.DefaultPath()
}
