// Package install emits the shell snippet that wires slug functions
// back into the user's shell.
//
// Each generated function is a one-liner that calls back into the kxp binary
// with its own name as context. All the dispatch smarts live in the binary;
// the shell functions are dumb pipes.
//
// Example output:
//
//	# auto-generated by `kxp install` — do not edit
//	kclo(){ kxp dispatch clo "$@"; }
//	ksys(){ kxp dispatch sys "$@"; }
//	kcil(){ kxp dispatch cil "$@"; }
//	...
//	alias kxpd="kxp dispatch"   # optional alternate invocation: kxpd clo
//
// Source the output from ~/.bashrc:
//
//	kxp install >> ~/.bashrc
//
// Or write to a standalone file and source that:
//
//	kxp install > ~/.config/kxp/slugs.sh
//	echo 'source ~/.config/kxp/slugs.sh' >> ~/.bashrc
package install

import (
	"fmt"
	"io"
	"strings"

	"github.com/weefarm/KubeXPander/internal/config"
)

// Emit writes the shell snippet for the given config to w.
//
// The snippet defines one function per slug (plain and filtered), plus
// the all-namespaces slug. Each function is `k<name>(){ kxp dispatch <name> "$@"; }`.
//
// An `kxpd` alias is also emitted so users can invoke `kxpd clo` as an
// alternate style (equivalent to `kxp dispatch clo`).
//
// Bash completion functions are emitted too, so `kclo <TAB>` completes pod
// names and `kclo rmf <TAB>` completes resource types. Completion requires
// `bash-completion` to be installed and `kxp` to be on $PATH.
func Emit(cfg *config.Config, w io.Writer) error {
	header := `# auto-generated by ` + "`kxp install`" + ` — do not edit by hand.
# Source this from your ~/.bashrc (or ~/.zshrc) to get slug functions.
# Re-run ` + "`kxp install`" + ` after editing ~/.config/kxp/slugs.yaml.
#
# Terminology: a "slug" is a short namespace alias. ` + "`kclo`" + ` dispatches to
# the ` + "`cloudflare`" + ` namespace — ` + "`k`" + ` is the prefix, ` + "`clo`" + ` is the slug.
`
	if _, err := fmt.Fprintln(w, header); err != nil {
		return err
	}

	// Optional kxpd alias: `alias kxpd="kxp dispatch"` so users can do `kxpd clo`.
	if _, err := fmt.Fprintln(w, `alias kxpd="kxp dispatch"  # alternate invocation: kxpd clo == kclo`); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}

	// All-namespaces slug (e.g. kall).
	allName := "k" + cfg.AllSlug
	if _, err := fmt.Fprintf(w, "%s(){ kxp dispatch %s \"$@\"; }\n", allName, cfg.AllSlug); err != nil {
		return err
	}

	// Plain slugs.
	for _, name := range sortedKeys(cfg.Slugs) {
		fn := "k" + name
		if _, err := fmt.Fprintf(w, "%s(){ kxp dispatch %s \"$@\"; }\n", fn, name); err != nil {
			return err
		}
	}

	// Filtered slugs.
	for _, name := range sortedKeysFiltered(cfg.Filtered) {
		fn := "k" + name
		if _, err := fmt.Fprintf(w, "%s(){ kxp dispatch %s \"$@\"; }\n", fn, name); err != nil {
			return err
		}
	}

	// Built-in cluster-scoped getters (kgn, kns). Emitted after slug functions
	// so they're always available; Dispatch resolves user slugs first, so a
	// user slug named `gn` or `ns` takes precedence over the built-in.
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, clusterGetSnippet); err != nil {
		return err
	}

	// Bare `lsf` guard — prints usage so it can't fire by accident.
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, gfGuardSnippet); err != nil {
		return err
	}

	// Completion block.
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, completionHeader); err != nil {
		return err
	}
	for _, name := range cfg.Names() {
		fn := "k" + name
		if _, err := fmt.Fprintf(w, completionPerShortcut, fn); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintln(w, "complete -F _kxp_dispatch_complete k"+cfg.AllSlug); err != nil {
		return err
	}
	for _, name := range cfg.Names() {
		if _, err := fmt.Fprintln(w, "complete -F _kxp_dispatch_complete k"+name); err != nil {
			return err
		}
	}
	// Completions for built-in cluster getters.
	if _, err := fmt.Fprintln(w, "complete -F _kxp_dispatch_complete kgn"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "complete -F _kxp_dispatch_complete kns"); err != nil {
		return err
	}

	return nil
}

// clusterGetSnippet defines the built-in cluster-scoped getter functions
// (kgn, kns). These are always emitted by `kxp install` regardless of the
// user's slug config; Dispatch resolves user slugs first, so a user-defined
// `gn` or `ns` slug takes precedence over the built-in.
const clusterGetSnippet = `# Built-in cluster-scoped getters (not namespace slugs).
#   kgn        -> kubectl get nodes
#   kgn o      -> kubectl get nodes -o wide
#   kns        -> kubectl get namespaces
#   kns o      -> kubectl get namespaces -o wide
# Anything else after kgn/kns is passed straight to kubectl (describe, label, ...).
kgn(){ kxp dispatch gn "$@"; }
kns(){ kxp dispatch ns "$@"; }
`

const gfGuardSnippet = `# Bare lsf is intentionally a no-op that prints usage; use kall lsf or
# k<slug> lsf for an actual finalizer scan.
lsf(){
  echo "Usage: kall lsf                       (whole-cluster scan)" >&2
  echo "       k<slug> lsf                    (e.g. kclo lsf — single namespace)" >&2
  return 1
}
`

const completionHeader = `# Bash completion: completes resource types after rmf, falls back to
# kubectl's own completion for everything else.
_kxp_dispatch_complete(){
  local cur prev words cword
  _init_completion 2>/dev/null || {
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
  }
  case "${COMP_WORDS[1]}" in
    rmf)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "pods deployments statefulsets daemonsets replicasets persistentvolumeclaims services ingress configmaps secrets namespaces persistentvolumes deployment pod pvc svc ns deploy sts ds" -- "$cur") )
        return
      fi
      ;;
  esac
  COMPREPLY=( $(compgen -f -- "$cur") )
}
`

const completionPerShortcut = `complete -F _kxp_dispatch_complete %s
`

// sortedKeys returns map keys sorted alphabetically (deterministic output).
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sortStrings(keys)
	return keys
}

func sortedKeysFiltered(m map[string]config.FilteredSlug) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sortStrings(keys)
	return keys
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
	_ = strings.TrimSpace // keep import used if we extend later
}
